language: c
dist: bionic
sudo: false
os:
  - linux
  - osx

notifications:
  email: false

addons:
  homebrew:
    update: true
    packages:
      - llvm
      - qemu
      - xorriso
      - mtools
      - i386-elf-grub
  apt:
    packages:
      - llvm-8
      - lld-8
      - clang-8
      - qemu
      - mtools
      - grub2
      - xorriso

install:
  - "if [[ $TRAVIS_OS_NAME == linux ]]; then pyenv global 3.7.1; fi"
  - pip3 install -r tools/requirements.txt

script:
  - defconfig misc/ci/$TRAVIS_OS_NAME.config
  - make reloadconfig
  - make info
  - make -j2
  - make run
